version: '3.8'
services:
  file-service:
    build: .
    image: inf326-file-service:latest
    ports:
      - "8000:8000"
    environment:
      - FILE_SERVICE_DB=/data/filemeta.db
      - FILE_SERVICE_STORAGE=/data/storage
      # - FILE_SERVICE_EVENT_HOOKS=http://moderation:9001/webhook,http://search:9002/webhook
    volumes:
      - ./data:/data
    restart: unless-stopped

  # Optional: simple webhook receiver for local testing (echoes received events)
  webhook-receiver:
    image: hashicorp/http-echo:0.2.3
    command: ["-text=ok"]
    ports:
      - "9001:5678"
